development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal-planner_development
  pool: 5
  username: root
  password: luke2i34
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal-planner_test
  pool: 5
  username: root
  password: luke2i34
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meal-planner_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock